# Generated by Django 2.2.1 on 2019-10-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio',
            new_name='portfolio_site',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='picture',
            new_name='profile_pic',
        ),
    ]
